version: "3.3"
networks:
  laravel:
services:
  nginx:
    image: nginx:stable-alpine
    container_name:nginx
    port:
      - "3000:3000*
    volumes
      - ./
    depend_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    networks:
      - laravel

  php:
    networks:
      - laravel